# frozen_string_literal: true

source "https://rubygems.org"

gem 'bcrypt'
gem 'mysql2'
gem 'mysql2-cs-bind'
gem 'puma'
gem 'sinatra'
gem 'sinatra-contrib'

gem "datadog-ci", "= 0.3.0"
gem "ddtrace", "= 1.16.2", :require => "ddtrace/auto_instrument"
