name: deploy
on: [ workflow_dispatch ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: ssh login
        env:
          PRIVATE_KEY: ${{ secrets.SECRET }}
          TARGET_IP: ${{ secrets.TARGET_IP3 }}
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 700 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -p 22 -H "$TARGET_IP" >> ~/.ssh/known_hosts
          scp -i ~/.ssh/id_rsa -r ./webapp/ruby isucon@$TARGET_IP:~/webapp
          scp -i ~/.ssh/id_rsa -r ./etc/mysql/mysql.conf.d/mysqld.cnf isucon@$TARGET_IP:/etc/mysql/mysql.conf.d
          scp -i ~/.ssh/id_rsa -r ./etc/nginx/isupipe.conf isucon@$TARGET_IP:/etc/nginx/sites-enabled
          scp -i ~/.ssh/id_rsa -r ./etc/nginx/nginx.conf isucon@$TARGET_IP:/etc/nginx
          ssh -i ~/.ssh/id_rsa isucon@$TARGET_IP "sudo systemctl restart mysql"
          ssh -i ~/.ssh/id_rsa isucon@$TARGET_IP "sudo systemctl restart nginx.service"
          ssh -i ~/.ssh/id_rsa isucon@$TARGET_IP "sudo systemctl daemon-reload"
          ssh -i ~/.ssh/id_rsa isucon@$TARGET_IP "sudo systemctl restart isupipe-ruby.service"

